
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ERPAnimalia.EntityFramework
{

using System;
    using System.Collections.Generic;
    
public partial class SucProducto
{

    public System.Guid IdSucursalProducto { get; set; }

    public System.Guid IdProducto { get; set; }

    public int IdSucursal { get; set; }

    public double Cantidad { get; set; }

}

}
